Cypress.Commands.add('Login', ()=>{
    cy.visit('https://front.serverest.dev/login')
    cy.get('#email').type('qa@qa.com')
    cy.get('#password').type('123456')
    cy.contains("Entrar").click()
    cy.contains("Bem Vindo").should('be.visible')
})
Cypress.Commands.add('Cadastra_Usuario', ()=>{
    cy.visit('https://front.serverest.dev/login')
    cy.contains('Login').should('be.visible')
    cy.contains('Cadastre-se').click()
    cy.get('#nome').type('TESTE QA')
    cy.get('#email').type('qa@qa.com')
    cy.get('#password').type('123456')
    cy.get('#administrador').check()
    cy.contains("button","Cadastrar").click()
    cy.contains('Cadastro realizado com sucesso').should('be.visible')
})
Cypress.Commands.add('Lista_Usuario', ()=>{
    cy.visit('https://front.serverest.dev/admin/home')
    cy.get('[data-testid="listarUsuarios"]').click()
    cy.contains("td","TESTE QA").should('be.visible')
    cy.contains("td","qa@qa.com").should('be.visible')
    cy.contains("td","123456").should('be.visible')
    cy.contains("td","true").should('be.visible')
})
Cypress.Commands.add('Cadastrar_Produtos', ()=>{
    cy.visit('https://front.serverest.dev/admin/home')
    cy.contains("li","Cadastrar Produtos").click()
    cy.get('#nome').type('PS5')
    cy.get('#price').type('3000')
    cy.get('#description').type('PS5 + 2 Controles + Jogo')
    cy.get('#quantity').type('600')
    cy.get('#imagem').as('fileInput').attachFile('PS5.jpg')
    cy.contains("button",'Cadastrar').click()
})
Cypress.Commands.add('Listar_Produtos', ()=>{
    cy.visit('https://front.serverest.dev/admin/home')
    cy.get('[data-testid="listarProdutos"]').click()
    cy.contains("td","PS5").should('be.visible')
    cy.contains("td","3000").should('be.visible')
    cy.contains("td","PS5 + 2 Controles + Jogo").should('be.visible')
    cy.contains("td","600").should('be.visible')
})
Cypress.Commands.add('Relatórios', ()=>{
    cy.visit('https://front.serverest.dev/admin/home')
    cy.contains("Ver").click()
    cy.contains("Em construção aguarde").should('be.visible')
})
Cypress.Commands.add('Excluir_Produto', ()=>{
    cy.visit('https://front.serverest.dev/admin/home')
    cy.get('[data-testid="listarProdutos"]').click()
    cy.get(':nth-child(454) > :nth-child(6) > .row > .btn-danger').click()
    cy.contains("td","PS5").should('not.exist')
})
Cypress.Commands.add('Excluir_Usuário', ()=>{
    cy.visit('https://front.serverest.dev/admin/home')
    cy.get('[data-testid="listarUsuarios"]').click()
    cy.contains("TESTE QA").should('be.visible')
    cy.contains("qa@qa.com").should('be.visible')
    cy.get(':nth-child(665) > :nth-child(3)')
      .invoke('val').then((valor)=>{const senha = valor;
      expect(senha).to.equal('')}) 
})
Cypress.Commands.add('Cadastra_Usuario_inv', ()=>{
    cy.visit('https://front.serverest.dev/login')
    cy.contains('Login').should('be.visible')
    cy.contains('Cadastre-se').click()
    cy.get('#nome').type('TESTE QA')
    cy.get('#email').type('qa@qa.com')
    cy.get('#password').type('123456')
    cy.get('#administrador').check()
    cy.contains("button","Cadastrar").click()
    cy.contains('Este email já está sendo usado').should('be.visible')
})